Remove -fpic from Windows Cuda issue with the but for ipc-toolkit with vcpkg on windows
Continuous-Collision-Detection/Scalable-CCD pull request #5
Opened 2024-09-24 16:52 UTC by antoinebou12

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.41.34120.0
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/nvcc.exe
-- The CUDA compiler identification is NVIDIA 12.6.68

![image](https://github.com/user-attachments/assets/895f05f9-720b-4d44-a1ca-ca8a47d2723b)

2024-09-24 20:19 UTC, zfergus requested changes

2024-09-24 20:19 UTC, zfergus commented on CMakeLists.txt
> +  set_target_properties(scalable_ccd PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
Revert this change as it only moved the line.

2024-09-24 20:19 UTC, zfergus commented on CMakeLists.txt
> +  # Enable separable compilation for CUDA
Delete this duplicate comment.

2024-09-24 20:19 UTC, zfergus commented on CMakeLists.txt
> +    # Add rpath for CUDA on macOS
Delete duplicate comment

2024-09-25 12:05 UTC, Q-Minh commented
The problem is not with the platform, it's with how the flags are passed to the underlying compiler (nvcc). Position independent code is not specific to Windows. Just set the [`POSITION_INDEPENDENT_CODE`](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html) property to ON for the relevant target, or set the global [`CMAKE_POSITION_INDEPENDENT_CODE`](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html#variable:CMAKE_POSITION_INDEPENDENT_CODE). CMake will know not to add the `-fPIC` flag when nvcc is invoked versus when the native build tool is invoked.

2024-09-25 18:14 UTC, zfergus requested changes

2024-09-25 18:14 UTC, zfergus commented on CMakeLists.txt
> +  set(CMAKE_POSITION_INDEPENDENT_CODE ON)
This is already set to ON in this file.

2024-09-25 18:14 UTC, zfergus commented on CMakeLists.txt
> +  set_target_properties(scalable_ccd PROPERTIES CUDA_SEPARABLE_COMPILATION ON POSITION_INDEPENDENT_CODE ON)
This does not need to be set as the global option is already set to ON

2024-09-26 19:12 UTC, zfergus approved these changes

2024-09-27 03:37 UTC, merged